import React from 'react';

// Paleta de diseño clínico unificada DentVision
export const colors = {
  bgWindow: '#FFFFFF',
  bgPage: '#F8FAFC',
  primary: '#0284C7',
  primaryHover: '#0369A1',
  primaryAccent: '#38BDF8',
  textMain: '#0F172A',
  textSecondary: '#475569',
  textMuted: '#64748B',
  border: '#E2E8F0',
  badgeBg: '#F0F9FF',
  success: '#10B981',
};

export const styles: Record<string, React.CSSProperties> = {
  pageContainer: {
    minHeight: '100vh',
    backgroundColor: colors.bgPage,
    fontFamily: "'DM Sans', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
    padding: '0 0 60px 0',
    margin: 0,
    width: '100%',
    boxSizing: 'border-box',
  },
  contentContainer: {
    maxWidth: '860px',
    margin: '36px auto 0 auto',
    padding: '0 24px',
  },
  headerSection: {
    marginBottom: '32px',
    textAlign: 'left',
  },
  title: {
    fontSize: '30px',
    fontWeight: '700',
    color: colors.textMain,
    marginBottom: '8px',
    letterSpacing: '-0.025em',
  },
  subtitle: {
    fontSize: '15px',
    color: colors.textMuted,
    lineHeight: '1.5',
    margin: 0,
  },
  card: {
    backgroundColor: colors.bgWindow,
    borderRadius: '16px',
    padding: '32px',
    border: `1px solid ${colors.border}`,
    boxShadow: '0 4px 12px -2px rgba(0, 0, 0, 0.05)',
    marginBottom: '28px',
  },
  cardTitle: {
    fontSize: '18px',
    fontWeight: '700',
    color: colors.textMain,
    marginBottom: '20px',
    borderBottom: `1px solid ${colors.border}`,
    paddingBottom: '12px',
  },
  formGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
    marginBottom: '20px',
  },
  gridTwoColumns: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(260px, 1fr))',
    gap: '20px',
  },
  label: {
    fontSize: '13.5px',
    fontWeight: '600',
    color: colors.textMain,
  },
  input: {
    width: '100%',
    height: '46px',
    padding: '0 16px',
    fontSize: '14.5px',
    borderRadius: '8px',
    border: `1px solid ${colors.border}`,
    backgroundColor: '#FFFFFF',
    color: colors.textMain,
    outline: 'none',
    boxSizing: 'border-box',
    fontWeight: '400',
    transition: 'border-color 0.2s ease, box-shadow 0.2s ease',
  },
  select: {
    width: '100%',
    height: '46px',
    padding: '0 16px',
    fontSize: '14.5px',
    borderRadius: '8px',
    border: `1px solid ${colors.border}`,
    backgroundColor: '#FFFFFF',
    color: colors.textMain,
    outline: 'none',
    boxSizing: 'border-box',
    cursor: 'pointer',
    fontWeight: '400',
  },
  checkboxGroup: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    padding: '10px 0',
    cursor: 'pointer',
  },
  checkbox: {
    width: '18px',
    height: '18px',
    cursor: 'pointer',
    accentColor: colors.primary,
  },
  checkboxLabel: {
    fontSize: '14px',
    color: colors.textSecondary,
    fontWeight: '500',
  },
  actionsContainer: {
    display: 'flex',
    justifyContent: 'flex-end',
    alignItems: 'center',
    gap: '16px',
    marginTop: '16px',
  },
  saveButton: {
    background: 'linear-gradient(135deg, #0284C7 0%, #0369A1 100%)',
    color: '#FFFFFF',
    border: 'none',
    padding: '12px 28px',
    borderRadius: '8px',
    fontSize: '14.5px',
    fontWeight: '600',
    cursor: 'pointer',
    boxShadow: '0 4px 12px rgba(2, 132, 199, 0.25)',
    transition: 'all 0.2s ease',
  },
  successBadge: {
    backgroundColor: '#F0FDF4',
    color: '#166534',
    padding: '8px 16px',
    borderRadius: '8px',
    fontWeight: '600',
    fontSize: '13.5px',
    border: '1px solid #BBF7D0',
  },
};
